name: Deploy to GH-Pages

on:
  push:
    branches: [ main deploy ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build
      
      - name: Quick setup
        run: |
          git config --global user.name "Mukesh Gurpude"
          git config --global user.email "mukeshgurpude02@gmail.com"

      - name: Deploy
        run: yarn deploy
